name: Build mod

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build mod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'dragonwell'
          java-version: '17'
          cache: gradle # Only cache stuff since test build action happen mostly

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: mkdir (1/5)
        run: mkdir run
      - name: mkdir (2/5)
        run: mkdir run/external-mods
      - name: download (3/4)
        run: curl -vL 'https://cdn.modrinth.com/data/QejnMYJo/versions/KDqr1s3P/ThermalExtra-3.3.0-1.20.1.jar' -o run/external-mods/ThermalExtra-3.3.0-1.20.1.jar
      - name: verify (4/4)
        run: ls -l run/external-mods && mv ThermalExtra-3.3.0-1.20.1.jar ThermalExtra.jar && ls -l run/external-mods
      - name: Build with Gradle
        run: ./gradlew jar
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MekanismCEu
          path: build/libs